### ISSUE TITLE
quadrangle / rotated bbox

### ISSUE THREAD

**Issue by soldierofhell** [clovaai/deep-text-recognition-benchmark#22]
Hi,
Thank you for this repo and great survey of current state-of-art methods.
I wonder what was your approach for annotations like ICDAR which are in form of quadrangles (usually it's rotated bbox). Have you de-rotated it first or just use bigger axis aligned bbox?
On the other hand, modern detection methods are able to predict rotation or even masks. So spatial transformation in recognition step is not necessary?

Records,

**Comment by ku21fan** [comment]
Hello @soldierofhell 

1. We tried both of them, and usually use de-rotated box. 
The performance gap between them seems to vary depending on the dataset.
Thus, it is worth trying both for your own dataset.

2. If detection methods perfectly crop the word, probably the spatial transformation step would not be necessary.
But, in my opinion, spatial transformation still worth it. 
Because the detection methods do not perfectly crop the word yet (its hard especially on irregular datasets), and thus spatial transformation could enhance detection result as mentioned in [ASTER paper](https://ieeexplore.ieee.org/abstract/document/8395027) (See section 5). 
and also spatial transformation might reduce the burden of the detector :)

best

**Comment by soldierofhell** [comment]
Thanks for clarification

In my opinion rotation of text is a problem when you have multiple lines of text (or even text with some boundaries). Then in bigger axis aligned bbox you have a mix of two lines for some steps and this can be confusing (of course in theory fiducial points should detect the proper line).

By the way, do you know any good tool for rotated bbox annotations? VIA recently introduced rotated ellipse, but didn't have rotated bbox yet

**Comment by ku21fan** [comment]
I don't know the annotation tools well...
