### ISSUE TITLE
strange accuracy in IC03

### ISSUE THREAD

**Issue by techkang** [clovaai/deep-text-recognition-benchmark#32]
I found that when using Attn, the result is always better than using CTC except in None+ResNet+BiLSTM and testing on IC03. What is possible interpretation of this result?

**Comment by ku21fan** [comment]
Hello, 

That would be an interesting point.
I assume that using CTC is better than using Attn on some images of IC03, which results in 0.3~0.4 % higher accuracy.

In my opinion, investigating those images would be needed for interpretation. 
However, it would be a time-consuming task since that is only one exception and the accuracy gap is relatively marginal.
Thus, I'm afraid that I have no time to investigate it deeply now.

If you want to interpret the accuracy gap between them, investigate them by using this repo.
You can train both of None-ResNet-BiLSTM-CTC and None-ResNet-BiLSTM-Attn and evaluate them on IC03 dataset with this repo.

Best.
