### ISSUE TITLE
test ctc model it is giving runtime error?

### ISSUE THREAD

**Issue by mythuven** [clovaai/deep-text-recognition-benchmark#41]
when I trained the algorithm with the prediction CTC and when I going for test demo.py I
![IMG_20190725_201840](https://user-images.githubusercontent.com/37474491/61936902-4695c680-afab-11e9-8111-f0754268e3e6.jpg)

 am getting the following error.

RuntimeError: storage has wrong size : expected -5510384958902273621 got 294912

**Comment by YacobBY** [comment]
Did you use the --Predicion CTC instead of  --Prediction Attn in the args?

If you trained on CTC your run command should now be something like:

CUDA_VISIBLE_DEVICES=0 python3 test.py  --eval_data data_lmdb_release/evaluation --benchmark_all_eval  --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction CTC  --saved_model saved_models/TPS-ResNet-BiLSTM-CTC-Seed1111/best_accuracy.pth

**Comment by mythuven** [comment]
Hi Sir thanks for reply

We used the below command to train

CUDA_VISIBLE_DEVICES=0 python3 train.py \
--train_data data_lmdb_release/training --valid_data
data_lmdb_release/validation \
--select_data MJ-ST --batch_ratio 0.5-0.5 \
--Transformation None --FeatureExtraction VGG --SequenceModeling
BiLSTM --Prediction CTC

And when we are testing this with demo.py this command in local pc is
workiing
CUDA_VISIBLE_DEVICES=0 python3 demo.py \

--Transformation None --FeatureExtraction VGG --SequenceModeling
BiLSTM --Prediction CTC \
--image_folder demo_image/ \
--saved_model TPS-ResNet-BiLSTM-CTC.pth

but same these weight file's and same command with demo.py running on edge
I am getting the error runtime error:what I have posted as my issue.
Can you please explain this sir.

**Comment by ku21fan** [comment]
From the images and error messages, I guess the error comes from loading the model.
However, it looks that the code is not demo.py. 
The code changed, and thus we can't follow it.

We can not answer the modified code which we don't know.
Check your model architecture.
