### ISSUE TITLE
why error occured create_lmdb_dataset?

### ISSUE THREAD

**Issue by parksunwoo** [clovaai/deep-text-recognition-benchmark#57]
I created lmdb korean dataset in 9000 samples, but I have some problem.
I already set opt.character in train.py
```parser.add_argument('--character', type=str, default='가각간갇갈감갑값갓강갖같갚갛개객 ```

error occured 7
error occured 225
error occured 523
error occured 760
error occured 846
Written 1000 / 9000
...
error occured 8210
error occured 8289
error occured 8345
error occured 8497
error occured 8807
error occured 8899
error occured 8973
Created dataset with 8937 samples

somebody help me!

**Comment by parksunwoo** [comment]
**and error occured dataset in training ... num samples 2 or 0**

```bash
dataset_root: /data/data_lmdb_release/training
opt.select_data: ['basic', 'skew']
opt.batch_ratio: ['0.5', '0.5']  
dataset_root:    /data/data_lmdb_release/training    dataset: basic
sub-directory:  /basic   num samples: 2
num total samples of basic: 2 x 1.0 (total_data_usage_ratio) = 2
num samples of basic per batch: 192 x 0.5 (batch_ratio) = 96  
dataset_root:    /nipa/Sunwoo/data/data_lmdb_release/training    dataset: skew
sub-directory:  /skew    num samples: 2
num total samples of skew: 2 x 1.0 (total_data_usage_ratio) = 2
num samples of skew per batch: 192 x 0.5 (batch_ratio) = 96  
Total_batch_size:  96+96 = 192  
dataset_root:    /data/data_lmdb_release/validation  dataset: /
sub-directory:  /back       num samples: 0
sub-directory:  /blur    num samples: 2
sub-directory:  /dist    num samples: 0
```

**Comment by ku21fan** [comment]
Hello,

1. I guess something wrong happened in this function.
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/create_lmdb_dataset.py#L11

Try to change `imageBuf = np.frombuffer(...` to `imageBuf = np.fromstring(...`
This is the code for old version... 
I guess updating your numpy version would also work..

2. Try to train with `--data_filtering_off`
If your num samples more than 2 with this option, other data were filtered by this snippet https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/dataset.py#L129-L146.
In this case, check your `character` option or you should change the filtering logic for your task.

Otherwise, something wrong happened to your lmdb data. 
Check your lmdb data by adding `print(label)` into this line.
https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/dataset.py#L136

Hope it helps.
Best

**Comment by parksunwoo** [comment]
Thanks a lot. Try to train with `--data_filtering_off ` and train model now.
The exact cause is not yet known, creating datasets in the local environment sucess.
Thank you
