### ISSUE TITLE
different decode operation between ctc and attention in converter

### ISSUE THREAD

**Issue by bityigoss** [clovaai/deep-text-recognition-benchmark#68]
Thanks for the great work.
in my model when I set opt.Prediction='Attn', the predicted results of models often contain repetitive characters.
I noted that decode in ctc converter removed continues repeated characters, while attention converter did not.
Can attention converter do the same operation with CTC converter? 
https://github.com/clovaai/deep-text-recognition-benchmark/blob/fc62d2232d54c1e812115abe376d573e03db4119/utils.py#L44
https://github.com/clovaai/deep-text-recognition-benchmark/blob/fc62d2232d54c1e812115abe376d573e03db4119/utils.py#L95

**Comment by ku21fan** [comment]
Hello, 

In general, I guess that Attn can't do the same operation with CTC.
Because CTCloss uses [blank] token to separate repeated characters. (which Attn doesn't have)
For example, 
a) fffooo[blank]odd --> food (CTC with [blank] token)
b) fffooooodd--> fod (just removing repeated character, without [blank] token)

So, If you want to make CTC-like attention, you would need [blank] token for the above case.
However, in this case, I guess that you should insert the [blank] token between all repeated characters to training whether to separate.

Best.
