### ISSUE TITLE
how to get confidence score of each word using Attn

### ISSUE THREAD

**Issue by nbhupendra** [clovaai/deep-text-recognition-benchmark#82]
I dont want to calculate distance with gt. i want the confidence score for read word by Attn. Like suppose if  word read by attn is "hello" and is confidence is 99% or something so that i could discard non english or junk character or word. @ku21fan @YacobBY please help.

**Comment by nbhupendra** [comment]
@ku21fan Can you check if it is possible?

**Comment by ku21fan** [comment]
Hello, 

Sorry for the late reply.
I just commit codes about confidence scores. 
Please check and test recent version~ (test.py and demo.py)

P.S. Recent code may occur error in [`F.grid_sample(~~, align_corners=True)`](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py#L33)
because the attribute `align_corners` of F.grid_sample is introduced in PyTorch 1.3.0.
So you may need to remove `, align_corners=True` in [here](https://github.com/clovaai/deep-text-recognition-benchmark/blob/master/modules/transformation.py#L33) or upgrade PyTorch to 1.3.0 

Best
